AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - ".git/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "spec/**/*"
    - "node_modules/**/*"
    - "bin/**"
    - "Gemfile"
    - "Rakefile"
    - "app/channels/**/*"
    - "vendor/**/*"
    - "cap-exposer/**/*"

# 日本語のコメントアウトを許可する
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

#ガード節の使用をチェック
Style/GuardClause:
  MinBodyLength: 5

#クラス名の長さ
Metrics/ClassLength:
  Max: 200

#メソッドの長さ
Metrics/MethodLength:
  Max: 30

#行数
Metrics/LineLength:
  Enabled: false

#循環的複雑度のチェック
CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 40