AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - ".git/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "spec/**/*"
    - "node_modules/**/*"
    - "bin/**"
    - "Gemfile"
    - "Rakefile"
    - "app/channels/**/*"
    - "vendor/**/*"

# 日本語のコメントアウトを許可する
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false