version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Exposer
      - public_data:/Exposer/public
      - tmp_data:/Exposer/tmp
      - log_data:/Exposer/log
    depends_on:
      - db
    environment:
      RAILS_ENV: production
  db:
    image: mysql:8.0.19
    ports:
      - '3306:3306'
    env_file:
      - ./.env
    #environment:
      #DB_USERNAME: tsushima
      #DB_USERNAME: root
      #DB_PASSWORD: password
      #MYSQL_ROOT_PASSWORD: root
      #DB_HOSTNAME: db
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - public_data:/Exposer/public
      - tmp_data:/Exposer/tmp
    ports:
      - 80:80
volumes:
  mysql_data:
  public_data:
  tmp_data:
  log_data:
  sockets: