version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0.19
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: ci_db_exposer
    working_directory: ~/repo


workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop