version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0.19
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop